name: "Build"
on:
  push:

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Compile and install dependencies"
      run: |
        brew install macos/sdl2.rb sdl2_image dylibbundler

    - name: "Compile"
      run: |
        make MAC_APP=YES Brogue.app
      env:
        # 10.6 is the version targeted by the SDL build scripts
        MACOSX_DEPLOYMENT_TARGET: "10.6"

    - name: "Fix and bundle dylib references"
      run: |
        cd Brogue.app/Contents && dylibbundler -cd -b -x MacOS/brogue

    - name: "Upload artifact"
      uses: actions/upload-artifact@v1
      with:
        name: Brogue CE.app
        path: Brogue.app
